## Name    : Nandini ThimmireddyGari.
## ID          : AP19110010128.
## Branch : CSE, SRM University AP.

### Day13 Task(21-06-2021)

## Task
* Create arrays with different numpy data types.
**Numpy has 11 Datatypes and the characters used to represent them are:*

1. integer - i
2. boolean - b
3. unsigned integer - u
4. float - f
5. complex float - c
6. timedelta - m
7. datatime - M
8. object - O
9. string - S
10. unicode string - U
11. fixed chunk of memory for other type (void) - V

In [3]:
import numpy as np

###  1. Integer type

In [4]:
arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### 2. Boolean type

In [12]:
arr = np.array([1, 2, 3, 4], dtype='bool')

print(arr)
print(arr.dtype)

[ True  True  True  True]
bool


### 3. Unsigned Integer type

In [14]:
arr = np.array([1, 2, 3, 4], dtype=np.uintc)

print(arr)
print(arr.dtype)

[1 2 3 4]
uint32


### 4. Float type

In [7]:
arr = np.array([1, 2, 3, 4], dtype='f')

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


### 5. Complex float type

In [15]:
arr = np.array([1, 2, 3, 4], dtype=np.csingle)

print(arr)
print(arr.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex64


### 6. Timedelta type

In [5]:
a=np.timedelta64(3,'D')
print(a)
a.dtype

3 days


dtype('<m8[D]')

### 7. Date Time type

In [18]:
arr=np.array(['2005-02-25','2005-02-22','2006-03-25'],dtype='M')
print(arr)
print(arr.dtype)

['2005-02-25' '2005-02-22' '2006-03-25']
datetime64[D]


### 8. Object type

In [11]:
arr = np.array([1, 2, 3, 4], dtype='O')

print(arr)
print(arr.dtype)

[1 2 3 4]
object


### 9. String type

In [19]:
arr = np.array(["Nandini", "CSE", "Data Science"], dtype='S')

print(arr)
print(arr.dtype)

[b'Nandini' b'CSE' b'Data Science']
|S12


### 10. Unicode String type

In [6]:
a=np.array([u'\u0394', u'\265Z', u'\265F', u'\u2202r'])
print(a)
print(a.dtype)

['Δ' 'µZ' 'µF' '∂r']
<U2


### 11. Void

In [7]:
a=np.array([],dtype='V')
print(a)
print(a.dtype)

[]
|V8
